### ISSUE TITLE
Can you get this to build?

### ISSUE THREAD

**Issue by RZR666** [peterennis/aeion4#1]
I seem to have a lot of .js and .js.map files in the www folder.

ionic serve works fine though.

**Comment by peterennis** [comment]
The site here: https://aeion4.adaept.com/ is running with this code.
What is your ionic info?

**Comment by peterennis** [comment]
I just saw this: https://github.com/ionic-team/ionic-cli/issues/3258
I am running rc7
You are using Node 10.
Try with Node 8 LTS.

**Comment by peterennis** [comment]
Closed. Ionic 4 released.
